"""Azure DevOps pipeline generator."""

from __future__ import annotations

from ..models import PipelineSpec
from ..presets import LANGUAGE_TOOLS
from .base import BasePlatform


class AzureDevOpsGenerator(BasePlatform):
    """Generate Azure DevOps (azure-pipelines.yml) pipeline files."""

    @property
    def name(self) -> str:
        return "Azure DevOps"

    @property
    def icon(self) -> str:
        return "\U0001f537"  # blue diamond

    @property
    def filename(self) -> str:
        return "azure-pipelines.yml"

    # ---- public API ----

    def generate(self, spec: PipelineSpec) -> str:
        tools = LANGUAGE_TOOLS.get(spec.project.language, {})
        parts: list[str] = [self._header(spec, tools)]

        parts.append("stages:")
        if "lint" in spec.stages:
            parts.append(self._lint_stage(spec, tools))
        if "test" in spec.stages:
            parts.append(self._test_stage(spec, tools))
        if "security" in spec.stages:
            parts.append(self._security_stage(spec, tools))
        if "build" in spec.stages:
            deps = [s.title() for s in ("test", "security") if s in spec.stages]
            parts.append(self._build_stage(spec, tools, deps))
        if "deploy" in spec.stages and spec.deploy:
            parts.append(self._deploy_stages(spec))

        content = "\n".join(parts)
        return "\n".join(line.rstrip() for line in content.split("\n"))

    # ---- private helpers ----

    def _header(self, spec: PipelineSpec, tools: dict) -> str:
        ver_var = tools.get("version_var_azure", "langVersion")
        lines = [
            f"# {'=' * 77}",
            f"# {spec.project.name} — Azure DevOps Pipeline",
            "# Generated by pipeline-generator v1.0.0",
            "# https://github.com/SanjaySundarMurthy/pipeline-generator",
            f"# {'=' * 77}",
            "",
            "trigger:",
            "  branches:",
            "    include:",
            "      - main",
            "      - master",
            "",
            "pr:",
            "  branches:",
            "    include:",
            "      - main",
            "      - master",
            "",
            "variables:",
            f'  {ver_var}: "{spec.project.version}"',
        ]

        if "build" in spec.stages and spec.build:
            lines.append('  # registryConnection: "your-service-connection"')
            lines.append(f'  # imageName: "{spec.project.name}"')

        lines.append("")
        return "\n".join(lines)

    def _setup_task(self, tools: dict) -> list[str]:
        """Language setup task for Azure DevOps."""
        task = tools.get("azure_setup_task", "")
        key = tools.get("azure_version_key", "")
        ver_var = tools.get("version_var_azure", "langVersion")
        if not task:
            return []
        return [
            f"          - task: {task}",
            "            inputs:",
            f"              {key}: $({ver_var})",
            f'            displayName: "Setup {tools.get("setup_key", "runtime")}"',
        ]

    def _lint_stage(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "  # ---- Lint & Format ----",
            "  - stage: Lint",
            '    displayName: "Lint & Format"',
            "    jobs:",
            "      - job: Lint",
            "        pool:",
            '          vmImage: "ubuntu-latest"',
            "        steps:",
        ]
        lines.extend(self._setup_task(tools))

        # Node.js needs deps first
        if tools.get("needs_deps_for_lint"):
            lines.append(f"          - script: {tools['install_deps']}")
            lines.append('            displayName: "Install dependencies"')

        if spec.lint and spec.lint.tools:
            lint_tools = tools.get("lint_tools", {})

            installs = []
            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                if cfg.get("install"):
                    installs.append(cfg["install"])

            if installs:
                cmd = (
                    " && ".join(installs)
                    if len(installs) <= 2
                    else "\n              ".join(installs)
                )
                lines.append(f"          - script: {cmd}")
                lines.append('            displayName: "Install linters"')

            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                runs = cfg.get("run", [])
                if len(runs) == 1:
                    lines.append(f"          - script: {runs[0]}")
                    lines.append(f'            displayName: "Run {name}"')
                elif runs:
                    lines.append("          - script: |")
                    for cmd in runs:
                        lines.append(f"              {cmd}")
                    lines.append(f'            displayName: "Run {name}"')

        lines.append("")
        return "\n".join(lines)

    def _test_stage(self, spec: PipelineSpec, tools: dict) -> str:
        ver_var = tools.get("version_var_azure", "langVersion")
        versions = tools.get("default_versions", [spec.project.version])
        task = tools.get("azure_setup_task", "")
        key = tools.get("azure_version_key", "")

        test_cmd = ""
        if spec.test:
            fws = tools.get("test_frameworks", {})
            test_cmd = fws.get(spec.test.framework, spec.test.framework)

        lines = [
            "  # ---- Test ----",
            "  - stage: Test",
            '    displayName: "Test"',
            "    dependsOn: Lint",
            "    jobs:",
            "      - job: Test",
            "        pool:",
            '          vmImage: "ubuntu-latest"',
        ]

        # Matrix strategy
        if len(versions) > 1:
            lines.append("        strategy:")
            lines.append("          matrix:")
            for v in versions:
                label = v.replace(".", "").replace("-", "")
                lines.append(f"            v{label}:")
                lines.append(f'              {ver_var}: "{v}"')

        lines.append("        steps:")

        if task:
            lines.append(f"          - task: {task}")
            lines.append("            inputs:")
            lines.append(f"              {key}: $({ver_var})")
            lines.append('            displayName: "Setup runtime"')

        lines.append(f"          - script: {tools.get('install_deps', 'echo no-op')}")
        lines.append('            displayName: "Install dependencies"')

        if test_cmd:
            # For Python, add JUnit output
            if spec.project.language == "python" and "pytest" in test_cmd:
                test_cmd = test_cmd.replace("pytest", "pytest --junitxml=test-results.xml")
            lines.append(f"          - script: {test_cmd}")
            lines.append('            displayName: "Run tests"')

        # Publish test results for Python / .NET
        if spec.project.language == "python":
            lines.extend(
                [
                    "          - task: PublishTestResults@2",
                    "            inputs:",
                    '              testResultsFormat: "JUnit"',
                    '              testResultsFiles: "test-results.xml"',
                    '            displayName: "Publish test results"',
                    "            condition: succeededOrFailed()",
                ]
            )
        if spec.test and spec.test.coverage and spec.project.language in ("python",):
            lines.extend(
                [
                    "          - task: PublishCodeCoverageResults@2",
                    "            inputs:",
                    '              codeCoverageTool: "Cobertura"',
                    '              summaryFileLocation: "coverage.xml"',
                    '            displayName: "Publish coverage"',
                ]
            )

        lines.append("")
        return "\n".join(lines)

    def _security_stage(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "  # ---- Security Scan ----",
            "  - stage: Security",
            '    displayName: "Security Scan"',
            "    dependsOn: Lint",
            "    jobs:",
            "      - job: Security",
            "        pool:",
            '          vmImage: "ubuntu-latest"',
            "        steps:",
        ]
        lines.extend(self._setup_task(tools))

        if spec.security and spec.security.tools:
            sec_tools = tools.get("security_tools", {})

            installs = []
            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                if cfg.get("install"):
                    installs.append(cfg["install"])

            if installs:
                lines.append("          - script: |")
                for cmd in installs:
                    lines.append(f"              {cmd}")
                lines.append('            displayName: "Install security tools"')

            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                run_cmd = cfg.get("run", "")
                if run_cmd:
                    lines.append(f"          - script: {run_cmd}")
                    lines.append(f'            displayName: "Run {name}"')
                    lines.append("            continueOnError: true")

        lines.append("")
        return "\n".join(lines)

    def _build_stage(self, spec: PipelineSpec, tools: dict, deps: list[str]) -> str:
        lines = [
            "  # ---- Build & Push Docker Image ----",
            "  - stage: Build",
            '    displayName: "Build & Push"',
            "    dependsOn:",
        ]
        for d in deps or ["Test"]:
            lines.append(f"      - {d}")

        lines.extend(
            [
                "    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
                "    jobs:",
                "      - job: Build",
                "        pool:",
                '          vmImage: "ubuntu-latest"',
                "        steps:",
                "          - task: Docker@2",
                '            displayName: "Build and push"',
                "            inputs:",
                "              command: buildAndPush",
                "              repository: $(imageName)",
                f"              dockerfile: {spec.build.dockerfile if spec.build else 'Dockerfile'}",
                "              containerRegistry: $(registryConnection)",
                "              tags: |",
                "                $(Build.BuildId)",
                "                latest",
            ]
        )

        lines.append("")
        return "\n".join(lines)

    def _deploy_stages(self, spec: PipelineSpec) -> str:
        if not spec.deploy:
            return ""

        lines: list[str] = []
        prev = "Build" if "build" in spec.stages else None

        for env in spec.deploy.environments:
            stage_id = f"Deploy{env.name.title()}"
            lines.append(f"  # ---- Deploy — {env.name.title()} ----")
            lines.append(f"  - stage: {stage_id}")
            lines.append(f'    displayName: "Deploy to {env.name.title()}"')

            if prev:
                lines.append(f"    dependsOn: {prev}")

            lines.append("    condition: succeeded()")
            lines.append("    jobs:")
            lines.append(f"      - deployment: {stage_id}")
            lines.append(f'        environment: "{env.name}"')
            lines.append("        pool:")
            lines.append('          vmImage: "ubuntu-latest"')
            lines.append("        strategy:")
            lines.append("          runOnce:")
            lines.append("            deploy:")
            lines.append("              steps:")
            lines.append(f'                - script: echo "Deploying to {env.name}..."')
            lines.append(f'                  displayName: "Deploy to {env.name.title()}"')
            lines.append("                  # Add your deployment commands here")
            lines.append("")

            prev = stage_id

        return "\n".join(lines)
