"""GitHub Actions pipeline generator."""

from __future__ import annotations

from ..models import PipelineSpec
from ..presets import LANGUAGE_TOOLS
from .base import BasePlatform


class GitHubActionsGenerator(BasePlatform):
    """Generate GitHub Actions workflow files."""

    @property
    def name(self) -> str:
        return "GitHub Actions"

    @property
    def icon(self) -> str:
        return "\U0001f419"  # octopus

    @property
    def filename(self) -> str:
        return ".github/workflows/ci.yml"

    # ---- public API ----

    def generate(self, spec: PipelineSpec) -> str:
        tools = LANGUAGE_TOOLS.get(spec.project.language, {})
        parts: list[str] = [self._header(spec, tools)]

        parts.append("jobs:")

        if "lint" in spec.stages:
            parts.append(self._lint_job(spec, tools))
        if "test" in spec.stages:
            parts.append(self._test_job(spec, tools))
        if "security" in spec.stages:
            parts.append(self._security_job(spec, tools))
        if "build" in spec.stages:
            prior = [s for s in ("lint", "test", "security") if s in spec.stages]
            parts.append(self._build_job(spec, tools, prior))
        if "deploy" in spec.stages and spec.deploy:
            parts.append(self._deploy_jobs(spec))

        content = "\n".join(parts)
        # Remove trailing whitespace per line
        return "\n".join(line.rstrip() for line in content.split("\n"))

    # ---- private helpers ----

    def _header(self, spec: PipelineSpec, tools: dict) -> str:
        ver_var = tools.get("version_var", "LANG_VERSION")

        lines = [
            f"# {'=' * 77}",
            f"# {spec.project.name} — GitHub Actions CI/CD Pipeline",
            "# Generated by pipeline-generator v1.0.0",
            "# https://github.com/SanjaySundarMurthy/pipeline-generator",
            f"# {'=' * 77}",
            f"name: {spec.project.name} CI/CD",
            "",
            "on:",
            "  push:",
            "    branches: [main, master]",
            "  pull_request:",
            "    branches: [main, master]",
            "",
            "env:",
            f'  {ver_var}: "{spec.project.version}"',
        ]

        if "build" in spec.stages and spec.build:
            registry = spec.build.registry or "ghcr.io"
            lines.append(f"  REGISTRY: {registry}")
            lines.append(f"  IMAGE_NAME: {self._gh('github.repository')}")

        lines.append("")
        return "\n".join(lines)

    def _setup_steps(self, spec: PipelineSpec, tools: dict, matrix: bool = False) -> list[str]:
        """Checkout + language setup steps."""
        lines = ["      - uses: actions/checkout@v4"]
        action = tools.get("setup_action")
        if not action:
            return lines

        key = tools["setup_key"]
        cache = tools.get("cache_key", "")
        ver_var = tools.get("version_var", "LANG_VERSION")

        version_ref = self._gh(f"matrix.{key}") if matrix else self._gh(f"env.{ver_var}")

        lines.append("")
        lines.append(f"      - uses: {action}")
        lines.append("        with:")
        lines.append(f"          {key}: {version_ref}")
        if cache:
            lines.append(f"          cache: {cache}")
        return lines

    def _lint_job(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "  # ---- Lint & Format ----",
            "  lint:",
            "    name: Lint & Format",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ]
        lines.extend(self._setup_steps(spec, tools))

        # Node.js needs deps for local eslint/prettier
        if tools.get("needs_deps_for_lint"):
            lines.append("")
            lines.append("      - name: Install dependencies")
            lines.append(f"        run: {tools['install_deps']}")

        if spec.lint and spec.lint.tools:
            lint_tools = tools.get("lint_tools", {})

            # Collect install commands
            installs = []
            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                if cfg.get("install"):
                    installs.append(cfg["install"])

            if installs:
                lines.append("")
                lines.append("      - name: Install linters")
                if len(installs) == 1:
                    lines.append(f"        run: {installs[0]}")
                else:
                    lines.append("        run: |")
                    for cmd in installs:
                        lines.append(f"          {cmd}")

            # Run commands
            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                runs = cfg.get("run", [])
                if len(runs) == 1:
                    lines.append("")
                    lines.append(f"      - name: Run {name}")
                    lines.append(f"        run: {runs[0]}")
                elif runs:
                    lines.append("")
                    lines.append(f"      - name: Run {name}")
                    lines.append("        run: |")
                    for cmd in runs:
                        lines.append(f"          {cmd}")

        lines.append("")
        return "\n".join(lines)

    def _test_job(self, spec: PipelineSpec, tools: dict) -> str:
        key = tools.get("setup_key", "version")
        versions = tools.get("default_versions", [spec.project.version])
        test_cmd = ""
        if spec.test:
            fws = tools.get("test_frameworks", {})
            test_cmd = fws.get(spec.test.framework, spec.test.framework)

        lines = [
            "  # ---- Test ----",
            "  test:",
            f"    name: Test ({self._gh(f'matrix.{key}')})",
            "    runs-on: ubuntu-latest",
            "    strategy:",
            "      matrix:",
            f"        {key}: {self._quote_versions(versions)}",
            "    steps:",
        ]
        lines.extend(self._setup_steps(spec, tools, matrix=True))

        lines.append("")
        lines.append("      - name: Install dependencies")
        lines.append(f"        run: {tools.get('install_deps', 'echo no-op')}")

        if test_cmd:
            lines.append("")
            lines.append("      - name: Run tests")
            lines.append(f"        run: {test_cmd}")

        # Coverage upload for supported languages
        if spec.test and spec.test.coverage and spec.project.language in ("python", "node"):
            last_ver = versions[-1] if versions else spec.project.version
            lines.append("")
            lines.append("      - name: Upload coverage")
            lines.append("        uses: codecov/codecov-action@v4")
            lines.append(f"        if: matrix.{key} == '{last_ver}'")
            lines.append("        with:")
            lines.append("          fail_ci_if_error: false")

        lines.append("")
        return "\n".join(lines)

    def _security_job(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "  # ---- Security Scan ----",
            "  security:",
            "    name: Security Scan",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ]
        lines.extend(self._setup_steps(spec, tools))

        if spec.security and spec.security.tools:
            sec_tools = tools.get("security_tools", {})

            # Install all security tools
            installs = []
            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                if cfg.get("install"):
                    installs.append(cfg["install"])

            if installs:
                lines.append("")
                lines.append("      - name: Install security tools")
                if len(installs) == 1:
                    lines.append(f"        run: {installs[0]}")
                else:
                    lines.append("        run: |")
                    for cmd in installs:
                        lines.append(f"          {cmd}")

            # Run each tool
            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                run_cmd = cfg.get("run", "")
                if run_cmd:
                    lines.append("")
                    lines.append(f"      - name: Run {name}")
                    lines.append(f"        run: {run_cmd}")
                    lines.append("        continue-on-error: true")

        lines.append("")
        return "\n".join(lines)

    def _build_job(self, spec: PipelineSpec, tools: dict, needs: list[str]) -> str:
        needs_str = "[" + ", ".join(needs) + "]" if needs else "[]"

        lines = [
            "  # ---- Build & Push Docker Image ----",
            "  build:",
            "    name: Build & Push",
            f"    needs: {needs_str}",
            "    runs-on: ubuntu-latest",
            "    if: github.event_name == 'push' && github.ref == 'refs/heads/main'",
            "    permissions:",
            "      contents: read",
            "      packages: write",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "",
            "      - name: Log in to Container Registry",
            "        uses: docker/login-action@v3",
            "        with:",
            f"          registry: {self._gh('env.REGISTRY')}",
            f"          username: {self._gh('github.actor')}",
            f"          password: {self._gh('secrets.GITHUB_TOKEN')}",
            "",
            "      - name: Extract metadata",
            "        id: meta",
            "        uses: docker/metadata-action@v5",
            "        with:",
            f"          images: {self._gh('env.REGISTRY')}/{self._gh('env.IMAGE_NAME')}",
            "          tags: |",
            "            type=sha",
            "            type=ref,event=branch",
            "            type=semver,pattern={{version}}",
            "",
            "      - name: Build and push",
            "        uses: docker/build-push-action@v5",
            "        with:",
            f"          context: {spec.build.context if spec.build else '.'}",
            "          push: true",
            f"          tags: {self._gh('steps.meta.outputs.tags')}",
            f"          labels: {self._gh('steps.meta.outputs.labels')}",
            "",
        ]
        return "\n".join(lines)

    def _deploy_jobs(self, spec: PipelineSpec) -> str:
        if not spec.deploy:
            return ""

        lines: list[str] = []
        prev_job = "build" if "build" in spec.stages else None

        for env in spec.deploy.environments:
            job_id = f"deploy-{env.name}"
            lines.append(f"  # ---- Deploy — {env.name.title()} ----")
            lines.append(f"  {job_id}:")
            lines.append(f"    name: Deploy to {env.name.title()}")

            if prev_job:
                lines.append(f"    needs: [{prev_job}]")

            lines.append("    runs-on: ubuntu-latest")

            if not env.auto_deploy:
                lines.append(
                    "    if: github.event_name == 'push' && github.ref == 'refs/heads/main'"
                )

            lines.append("    environment:")
            lines.append(f"      name: {env.name}")
            lines.append("    steps:")
            lines.append("      - uses: actions/checkout@v4")
            lines.append("")

            if spec.deploy.target == "kubernetes":
                secret_name = f"KUBE_CONFIG_{env.name.upper()}"
                lines.append(f"      - name: Deploy to {env.name.title()}")
                lines.append("        run: |")
                lines.append(f'          echo "Deploying to {env.name}..."')
                lines.append(
                    f"          # kubectl set image deployment/app "
                    f"app={self._gh('env.REGISTRY')}/{self._gh('env.IMAGE_NAME')}"
                    f":{self._gh('github.sha')}"
                )
                lines.append(f"          # Requires secret: {secret_name}")
            elif spec.deploy.target == "azure-webapp":
                lines.append("      - name: Login to Azure")
                lines.append("        uses: azure/login@v2")
                lines.append("        with:")
                lines.append(f"          creds: {self._gh('secrets.AZURE_CREDENTIALS')}")
                lines.append("")
                lines.append(f"      - name: Deploy to {env.name.title()}")
                lines.append("        uses: azure/webapps-deploy@v3")
                lines.append("        with:")
                lines.append(
                    f"          app-name: {self._gh('github.event.repository.name')}-{env.name}"
                )
            else:
                lines.append(f"      - name: Deploy to {env.name.title()}")
                lines.append("        run: |")
                lines.append(f'          echo "Deploying to {env.name}..."')
                lines.append("          # Add your deployment commands here")

            lines.append("")
            prev_job = job_id

        return "\n".join(lines)
