"""GitLab CI pipeline generator."""

from __future__ import annotations

from ..models import PipelineSpec
from ..presets import LANGUAGE_TOOLS
from .base import BasePlatform


class GitLabCIGenerator(BasePlatform):
    """Generate GitLab CI (.gitlab-ci.yml) pipeline files."""

    @property
    def name(self) -> str:
        return "GitLab CI"

    @property
    def icon(self) -> str:
        return "\U0001f98a"  # fox (GitLab)

    @property
    def filename(self) -> str:
        return ".gitlab-ci.yml"

    # ---- public API ----

    def generate(self, spec: PipelineSpec) -> str:
        tools = LANGUAGE_TOOLS.get(spec.project.language, {})
        parts: list[str] = [self._header(spec, tools)]

        if "lint" in spec.stages:
            parts.append(self._lint_job(spec, tools))
        if "test" in spec.stages:
            parts.append(self._test_job(spec, tools))
        if "security" in spec.stages:
            parts.append(self._security_job(spec, tools))
        if "build" in spec.stages:
            parts.append(self._build_job(spec, tools))
        if "deploy" in spec.stages and spec.deploy:
            parts.append(self._deploy_jobs(spec))

        content = "\n".join(parts)
        return "\n".join(line.rstrip() for line in content.split("\n"))

    # ---- private helpers ----

    def _header(self, spec: PipelineSpec, tools: dict) -> str:
        ver_var = tools.get("version_var", "LANG_VERSION")
        image = tools.get("image_template", "ubuntu:latest").format(version="${" + ver_var + "}")

        stages = [s for s in spec.stages if s != "deploy"] + (
            ["deploy"] if "deploy" in spec.stages else []
        )

        lines = [
            f"# {'=' * 77}",
            f"# {spec.project.name} — GitLab CI/CD Pipeline",
            "# Generated by pipeline-generator v1.0.0",
            "# https://github.com/SanjaySundarMurthy/pipeline-generator",
            f"# {'=' * 77}",
            "",
            "stages:",
        ]
        for s in stages:
            lines.append(f"  - {s}")

        lines.extend(
            [
                "",
                "variables:",
                f'  {ver_var}: "{spec.project.version}"',
            ]
        )

        # Add cache config for Python/Node
        cache_key = tools.get("cache_key", "")
        if cache_key == "pip":
            lines.extend(
                [
                    '  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"',
                    "",
                    "default:",
                    f"  image: {image}",
                    "",
                    "cache:",
                    "  paths:",
                    "    - .cache/pip",
                ]
            )
        elif cache_key == "npm":
            lines.extend(
                [
                    "",
                    "default:",
                    f"  image: {image}",
                    "",
                    "cache:",
                    "  paths:",
                    "    - node_modules/",
                ]
            )
        else:
            lines.extend(
                [
                    "",
                    "default:",
                    f"  image: {image}",
                ]
            )

        lines.append("")
        return "\n".join(lines)

    def _lint_job(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "# ---- Lint & Format ----",
            "lint:",
            "  stage: lint",
            "  script:",
        ]

        # Node.js needs deps first
        if tools.get("needs_deps_for_lint"):
            lines.append(f"    - {tools['install_deps']}")

        if spec.lint and spec.lint.tools:
            lint_tools = tools.get("lint_tools", {})

            # Install
            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                if cfg.get("install"):
                    lines.append(f"    - {cfg['install']}")

            # Run
            for name in spec.lint.tools:
                cfg = lint_tools.get(name, {})
                for cmd in cfg.get("run", []):
                    lines.append(f"    - {cmd}")

        lines.append("")
        return "\n".join(lines)

    def _test_job(self, spec: PipelineSpec, tools: dict) -> str:
        ver_var = tools.get("version_var", "LANG_VERSION")
        versions = tools.get("default_versions", [spec.project.version])
        image_tpl = tools.get("image_template", "ubuntu:latest")

        test_cmd = ""
        if spec.test:
            fws = tools.get("test_frameworks", {})
            test_cmd = fws.get(spec.test.framework, spec.test.framework)

        lines = [
            "# ---- Test ----",
            "test:",
            "  stage: test",
        ]

        # Matrix for multiple versions
        if len(versions) > 1:
            lines.append("  parallel:")
            lines.append("    matrix:")
            ver_list = ", ".join(f'"{v}"' for v in versions)
            lines.append(f"      - {ver_var}: [{ver_list}]")
            lines.append(f"  image: {image_tpl.format(version='${' + ver_var + '}')}")

        lines.extend(
            [
                "  script:",
                f"    - {tools.get('install_deps', 'echo no-op')}",
            ]
        )

        if test_cmd:
            # Add JUnit output for pytest
            if spec.project.language == "python" and "pytest" in test_cmd:
                test_cmd = test_cmd.replace("pytest", "pytest --junitxml=report.xml")
            lines.append(f"    - {test_cmd}")

        # Coverage regex for GitLab
        if spec.test and spec.test.coverage and spec.project.language == "python":
            lines.append(r"  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'")

        # Artifacts
        if spec.project.language == "python" and spec.test and spec.test.coverage:
            lines.extend(
                [
                    "  artifacts:",
                    "    when: always",
                    "    reports:",
                    "      junit: report.xml",
                    "      coverage_report:",
                    "        coverage_format: cobertura",
                    "        path: coverage.xml",
                ]
            )
        elif spec.project.language == "dotnet":
            lines.extend(
                [
                    "  artifacts:",
                    "    when: always",
                    "    reports:",
                    "      junit: TestResults/*.trx",
                ]
            )

        lines.append("")
        return "\n".join(lines)

    def _security_job(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "# ---- Security Scan ----",
            "security:",
            "  stage: security",
            "  script:",
        ]

        if spec.security and spec.security.tools:
            sec_tools = tools.get("security_tools", {})

            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                if cfg.get("install"):
                    lines.append(f"    - {cfg['install']}")

            for name in spec.security.tools:
                cfg = sec_tools.get(name, {})
                run_cmd = cfg.get("run", "")
                if run_cmd:
                    lines.append(f"    - {run_cmd} || true")

        lines.append("  allow_failure: true")
        lines.append("")
        return "\n".join(lines)

    def _build_job(self, spec: PipelineSpec, tools: dict) -> str:
        lines = [
            "# ---- Build & Push Docker Image ----",
            "build:",
            "  stage: build",
            "  image: docker:latest",
            "  services:",
            "    - docker:dind",
            "  variables:",
            '    DOCKER_TLS_CERTDIR: "/certs"',
            "  before_script:",
            "    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY",
            "  script:",
            "    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
            " -t $CI_REGISTRY_IMAGE:latest .",
            "    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA",
            "    - docker push $CI_REGISTRY_IMAGE:latest",
            "  rules:",
            '    - if: $CI_COMMIT_BRANCH == "main"',
            "",
        ]
        return "\n".join(lines)

    def _deploy_jobs(self, spec: PipelineSpec) -> str:
        if not spec.deploy:
            return ""

        lines: list[str] = []
        prev_job: str | None = None

        for env in spec.deploy.environments:
            job_id = f"deploy-{env.name}"
            lines.append(f"# ---- Deploy — {env.name.title()} ----")
            lines.append(f"{job_id}:")
            lines.append("  stage: deploy")
            lines.append("  script:")
            lines.append(f'    - echo "Deploying to {env.name}..."')
            lines.append("    # Add your deployment commands here")

            lines.append("  environment:")
            lines.append(f"    name: {env.name}")

            lines.append("  rules:")
            if env.auto_deploy:
                lines.append('    - if: $CI_COMMIT_BRANCH == "main"')
            else:
                lines.append('    - if: $CI_COMMIT_BRANCH == "main"')
                lines.append("      when: manual")

            if prev_job:
                lines.append("  needs:")
                lines.append(f"    - {prev_job}")

            lines.append("")
            prev_job = job_id

        return "\n".join(lines)
