"""Core pipeline generation engine — orchestrates spec loading + platform generators."""

from __future__ import annotations

from pathlib import Path

import yaml

from .models import (
    BuildConfig,
    DeployConfig,
    LintConfig,
    PipelineSpec,
    SecurityConfig,
    TestConfig,
)
from .platforms.azure import AzureDevOpsGenerator
from .platforms.github import GitHubActionsGenerator
from .platforms.gitlab import GitLabCIGenerator
from .presets import LANGUAGE_TOOLS, PRESETS

# Registry of all platform generators
PLATFORMS = {
    "github": GitHubActionsGenerator(),
    "azure": AzureDevOpsGenerator(),
    "gitlab": GitLabCIGenerator(),
}


def load_spec(path: str = "pipeline.yaml") -> PipelineSpec:
    """Load a pipeline spec from a YAML file."""
    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return PipelineSpec.from_dict(data)


def fill_defaults(spec: PipelineSpec) -> PipelineSpec:
    """Fill in default configs for stages that are listed but not configured.

    If a user lists 'lint' in stages but doesn't provide a lint config,
    we use sensible defaults for the detected language.
    """
    lang = spec.project.language
    tools = LANGUAGE_TOOLS.get(lang, {})

    if "lint" in spec.stages and not spec.lint:
        default_lint_tools = list(tools.get("lint_tools", {}).keys())[:1]
        spec.lint = LintConfig(tools=default_lint_tools)

    if "test" in spec.stages and not spec.test:
        test_fws = list(tools.get("test_frameworks", {}).keys())
        default_fw = test_fws[0] if test_fws else ""
        spec.test = TestConfig(framework=default_fw, coverage=True)

    if "security" in spec.stages and not spec.security:
        default_sec = list(tools.get("security_tools", {}).keys())
        spec.security = SecurityConfig(tools=default_sec)

    if "build" in spec.stages and not spec.build:
        spec.build = BuildConfig()

    if "deploy" in spec.stages and not spec.deploy:
        spec.deploy = DeployConfig()

    return spec


def generate_pipelines(
    spec: PipelineSpec,
    platform: str = "all",
    output_dir: str = ".",
    dry_run: bool = False,
) -> dict[str, str]:
    """Generate pipeline config files for one or all platforms.

    Args:
        spec: The pipeline specification.
        platform: 'github', 'azure', 'gitlab', or 'all'.
        output_dir: Directory to write generated files.
        dry_run: If True, generate content but don't write to disk.

    Returns:
        Dict mapping filename to generated content.
    """
    # Fill defaults for stages missing configs
    spec = fill_defaults(spec)

    if platform == "all":
        generators = list(PLATFORMS.values())
    else:
        gen = PLATFORMS.get(platform)
        if not gen:
            valid = ", ".join(PLATFORMS.keys())
            raise ValueError(f"Unknown platform: '{platform}'. Choose from: {valid}")
        generators = [gen]

    results: dict[str, str] = {}

    for gen in generators:
        content = gen.generate(spec)
        filepath = gen.filename
        results[filepath] = content

        if not dry_run:
            full_path = Path(output_dir) / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")

    return results


def create_spec_file(
    preset: str = "python",
    output_path: str = "pipeline.yaml",
    project_name: str = "",
) -> str:
    """Create a pipeline.yaml spec file from a preset.

    Returns the generated YAML content.
    """
    if preset not in PRESETS:
        valid = ", ".join(PRESETS.keys())
        raise ValueError(f"Unknown preset: '{preset}'. Choose from: {valid}")

    import copy

    spec = copy.deepcopy(PRESETS[preset])
    if project_name:
        spec.project.name = project_name

    content = render_spec_yaml(spec)
    Path(output_path).write_text(content, encoding="utf-8")
    return content


def render_spec_yaml(spec: PipelineSpec) -> str:
    """Render a PipelineSpec as a well-commented YAML string."""
    lines: list[str] = [
        "# =============================================================================",
        "# Pipeline Specification",
        "# Generated by pipeline-generator v1.0.0",
        "#",
        "# Edit this file to customize your CI/CD pipeline, then run:",
        "#   pipe-gen generate --platform all",
        "#",
        "# Docs: https://github.com/SanjaySundarMurthy/pipeline-generator",
        "# =============================================================================",
        "",
        "# Project metadata",
        "project:",
        f"  name: {spec.project.name}",
        f"  language: {spec.project.language}",
        f'  version: "{spec.project.version}"',
    ]

    if spec.project.framework:
        lines.append(f"  framework: {spec.project.framework}")
    else:
        lines.append("  # framework: fastapi       # Optional: fastapi | django | express | next")

    lines.extend(
        [
            "",
            "# Pipeline stages (in execution order)",
            "stages:",
        ]
    )
    for stage in spec.stages:
        lines.append(f"  - {stage}")
    if "deploy" not in spec.stages:
        lines.append("  # - deploy                 # Uncomment to enable deployment")

    if spec.lint:
        lines.extend(["", "# Linting configuration", "lint:", "  tools:"])
        for tool in spec.lint.tools:
            lines.append(f"    - {tool}")

    if spec.test:
        lines.extend(
            [
                "",
                "# Test configuration",
                "test:",
                f"  framework: {spec.test.framework}",
                f"  coverage: {str(spec.test.coverage).lower()}",
                f"  min_coverage: {spec.test.min_coverage}",
            ]
        )

    if spec.security:
        lines.extend(["", "# Security scanning", "security:", "  tools:"])
        for tool in spec.security.tools:
            lines.append(f"    - {tool}")

    if spec.build:
        lines.extend(
            [
                "",
                "# Build configuration",
                "build:",
                f"  type: {spec.build.type}",
                f"  dockerfile: {spec.build.dockerfile}",
                f"  registry: {spec.build.registry}",
            ]
        )

    if spec.deploy:
        lines.extend(
            [
                "",
                "# Deployment configuration",
                "deploy:",
                f"  target: {spec.deploy.target}",
                "  environments:",
            ]
        )
        for env in spec.deploy.environments:
            auto = str(env.auto_deploy).lower()
            lines.append(f"    - name: {env.name}")
            lines.append(f"      auto_deploy: {auto}")
    else:
        lines.extend(
            [
                "",
                "# Deployment (uncomment to enable)",
                "# deploy:",
                "#   target: kubernetes       # kubernetes | azure-webapp | aws-ecs | static",
                "#   environments:",
                "#     - name: staging",
                "#       auto_deploy: true",
                "#     - name: production",
                "#       auto_deploy: false",
            ]
        )

    lines.append("")
    return "\n".join(lines)
